export const FETCH_PROS_CONS_REQUEST = "FETCH_PROS_CONS_REQUEST";
export const FETCH_PROS_CONS_FAILURE = "FETCH_PROS_CONS_FAILURE";
export const FETCH_PROS_CONS_SUCCESS = "FETCH_PROS_CONS_SUCCESS";

export const ADD_PROS_CONS_REQUEST = "ADD_PROS_CONS_REQUEST";
export const ADD_PROS_CONS_FAILURE = "ADD_PROS_CONS_FAILURE";
export const ADD_PROS_CONS_SUCCESS = "ADD_PROS_CONS_SUCCESS";
